=== tejvirc/Platform/Hardware/Aristocrat.Monaco.Hardware.Contracts/Region.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- definition of types -->
  <xs:simpleType name="idtype">
    <xs:restriction base="xs:positiveInteger">
		<xs:minInclusive value="100" />
		<xs:maxInclusive value="999" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typetype">
    <xs:restriction base="xs:string">
      <xs:pattern value="[FGB]=[0-9]{1,3}" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="inttype">
    <xs:restriction base="xs:int">
		<xs:minInclusive value="0" />
		<xs:maxInclusive value="99999" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="rottype">
    <xs:restriction base="xs:positiveInteger">
		<xs:minInclusive value="1" />
		<xs:maxInclusive value="4" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="jsttype">
    <xs:restriction base="xs:positiveInteger">
		<xs:minInclusive value="1" />
		<xs:maxInclusive value="4" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="modifiertype">
    <xs:restriction base="xs:int">
		<xs:minInclusive value="0" />
		<xs:maxInclusive value="24" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="attrtype">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9])+(\+([0-9])+)*" />
    </xs:restriction>
  </xs:simpleType>

  <!-- definition of attributes -->
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="property" type="xs:string" />
  <xs:attribute name="id" type="idtype" />
  <xs:attribute name="x" type="inttype" />
  <xs:attribute name="px" type="xs:string" />
  <xs:attribute name="y" type="inttype" />
  <xs:attribute name="py" type="xs:string" />
  <xs:attribute name="dx" type="inttype" />
  <xs:attribute name="pdx" type="xs:string" />
  <xs:attribute name="dy" type="inttype" />
  <xs:attribute name="pdy" type="xs:string" />
  <xs:attribute name="rot" type="rottype" />
  <xs:attribute name="jst" type="xs:int" />
  <xs:attribute name="type" type="typetype" />
  <xs:attribute name="m1" type="modifiertype" />
  <xs:attribute name="m2" type="modifiertype" />
  <xs:attribute name="attr" type="attrtype" />

  <!-- definition of complex elements -->
  <xs:complexType name="dprtype">
    <xs:sequence>
      <xs:element name="D" type="xs:string" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute ref="name" use="required" />
    <xs:attribute ref="property" use="optional" />
    <xs:attribute ref="id" use="required" />
    <xs:attribute ref="x" use="required" />
    <xs:attribute ref="px" use="required" />
    <xs:attribute ref="y" use="required" />
    <xs:attribute ref="py" use="required" />
    <xs:attribute ref="dx" use="required" />
    <xs:attribute ref="pdx" use="required" />
    <xs:attribute ref="dy" use="required" />
    <xs:attribute ref="pdy" use="required" />
    <xs:attribute ref="rot" use="required" />
    <xs:attribute ref="jst" use="required" />
    <xs:attribute ref="type" use="required" />
    <xs:attribute ref="m1" use="required" />
    <xs:attribute ref="m2" use="required" />
    <xs:attribute ref="attr" use="required" />
  </xs:complexType>

  <xs:complexType name="dprcollectiontype">
    <xs:sequence>
      <xs:element name="DPR" type="dprtype" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- definition of root element -->
  <xs:element name="DPR_Collection" type="dprcollectiontype" />

</xs:schema>

=== tejvirc/Platform/Jurisdiction/Quebec-VLT/printable_regions.xml
<?xml version="1.0" encoding="UTF-8"?>
<DPR_Collection
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../bin/Region.xsd"
  xml:space="preserve">
    <DPR name="TextTicketLeft" id="100" x="28" px="00000" y="20" py="00020" dx="476" pdx="00504" dy="2000" pdy="01000" rot="1" jst="1" type="F=009" m1="1" m2="1" attr="001" property="left">
      <D></D>                                                                                                   
    </DPR>                                                                                                      
    <DPR name="TextTicketCenter" id="101" x="28" px="00000" y="20" py="00020" dx="476" pdx="00496" dy="2000" pdy="01000" rot="1" jst="2" type="F=009" m1="1" m2="1" attr="001" property="center">
      <D></D>                                                                                                   
    </DPR>                                                                                                      
    <DPR name="TextTicketRight" id="102" x="28" px="00000" y="20" py="00020" dx="476" pdx="00491" dy="2000" pdy="01000" rot="1" jst="3" type="F=009" m1="1" m2="1" attr="001" property="right">
     <D></D>                                                                                                    
    </DPR>                                                                                                      
    <DPR name="TextTicketTitle" id="103" x="28" px="00000" y="20" py="00000" dx="476" pdx="00504" dy="2000" pdy="01000" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="title">
     <D></D>                                                                                                    
    </DPR>                                                                                                      
    <DPR name="CashSlipTitle" id="106" x="216" px="00105" y="1051" py="00020" dx="89" pdx="00100" dy="1020" pdy="01020" rot="4" jst="2" type="F=003" m1="1" m2="1" attr="001" property="title localized">
      <D></D>                                                                            
    </DPR>                                                                                                      
    <DPR name="ValidationNo" id="107" x="28" px="00028" y="15" py="00015" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="validation number">
      <D></D>                                                                                                   
    </DPR>                                                                                                      
    <DPR name="CashSlipSeqNo" id="108" x="28" px="00028" y="50" py="00050" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="vlt sequence number">
      <D></D>                                                                                                   
    </DPR>                                                                                                      
    <DPR name="CashSlipPaperStatus" id="109" x="28" px="00028" y="85" py="00085" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="paper status">
      <D></D>                                                                                                   
    </DPR>                                                                                                      
    <DPR name="DateTime" id="110" x="28" px="00028" y="120" py="00120" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="datetime">
      <D></D>                                                                                                   
    </DPR>                                                                                                      
    <DPR name="License" id="111" x="28" px="00028" y="155" py="00155" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="license">
      <D></D>                                                                                         
    </DPR>                                                                                                      
    <DPR name="Online" id="112" x="28" px="00028" y="190" py="00190" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="online">
      <D></D>                                                                                           
    </DPR>                                                                                                      
    <DPR name="VignetteVersMac" id="113" x="378" px="00320" y="822" py="00000" dx="24" pdx="00064" dy="600" pdy="01020" rot="4" jst="2" type="F=007" m1="1" m2="1" attr="001" property="serial osversion mac">
      <D></D>                                                                                                   
    </DPR>                                                                                                      
    <DPR name="CashValue" id="114" x="450" px="00350" y="1051" py="00020" dx="70" pdx="00100" dy="1020" pdy="01020" rot="4" jst="2" type="F=002" m1="1" m2="1" attr="001" property="value">
      <D></D>                                                                                                   
    </DPR>                                                                                                      
    <DPR name="CashValueText" id="115" x="476" px="00414" y="1051" py="00020" dx="24" pdx="00064" dy="1020" pdy="01020" rot="4" jst="2" type="F=006" m1="1" m2="1" attr="001" property="value in words 1">
      <D></D>                                                                                                   
    </DPR>                                                                                                      
    <DPR name="CreditsText" id="116" x="508" px="00444" y="1051" py="00020" dx="24" pdx="00064" dy="1020" pdy="01020" rot="4" jst="2" type="F=007" m1="1" m2="1" attr="001" property="vlt credits">
      <D></D>                                                                                                   
    </DPR>                                                                                                     
    <DPR name="CashSlipBarcode" id="117" x="210" px="00180" y="175" py="00225" dx="108" pdx="00128" dy="724" pdy="00624" rot="4" jst="2" type="B=001" m1="4" m2="8" attr="128" property="barcode">
      <D></D>                                                                                                   
    </DPR>                                                                                                      
    <DPR name="EstablishmentName" id="121" x="108" px="00005" y="1051" py="00020" dx="65" pdx="00065" dy="1020" pdy="01020" rot="4" jst="2" type="F=003" m1="1" m2="1" attr="001" property="establishment name">
      <D></D>                                                                                                   
    </DPR>                                                                                                      
    <DPR name="FullAddress" id="122" x="122" px="00045" y="1051" py="00020" dx="65" pdx="00065" dy="1020" pdy="01020" rot="4" jst="2" type="F=003" m1="1" m2="1" attr="001" property="full address">
      <D></D>                                                                                                   
    </DPR>                                                                                                      
    <DPR name="CashSlipPaperLevel" id="134" x="28" px="00028" y="85" py="00085" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="paper level">
      <D></D>                                                                                                   
    </DPR>     
</DPR_Collection>

=== tejvirc/Platform/Jurisdiction/Oregon-VLT/printable_regions.xml
<?xml version="1.0" encoding="UTF-8"?>
<DPR_Collection
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../bin/Region.xsd"
  xml:space="preserve">
    <DPR name="TextTicketLeft" id="100" x="28" px="00000" y="20" py="00020" dx="476" pdx="00504" dy="2000" pdy="01000" rot="1" jst="1" type="F=009" m1="1" m2="1" attr="001" property="left">
      <D></D>
    </DPR>
    <DPR name="TextTicketCenter" id="101" x="28" px="00000" y="20" py="00020" dx="476" pdx="00496" dy="2000" pdy="01000" rot="1" jst="2" type="F=009" m1="1" m2="1" attr="001" property="center">
      <D></D>
    </DPR>
    <DPR name="TextTicketRight" id="102" x="28" px="00000" y="20" py="00020" dx="476" pdx="00491" dy="2000" pdy="01000" rot="1" jst="3" type="F=009" m1="1" m2="1" attr="001" property="right">
      <D></D>
    </DPR>
    <DPR name="TextTicketTitle" id="103" x="28" px="00000" y="20" py="00000" dx="476" pdx="00504" dy="2000" pdy="01000" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="title">
      <D></D>
    </DPR>
    <DPR name="TextTicketCenterAlt" id="104" x="28" px="00000" y="20" py="00020" dx="476" pdx="00496" dy="2000" pdy="01000" rot="1" jst="2" type="F=009" m1="1" m2="1" attr="001" property="center alt">
      <D></D>
    </DPR>
    <DPR name="CashSlipTitle" id="105" x="28" px="00028" y="15" py="00100" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=007" m1="1" m2="1" attr="001" property="title jackpot top">
      <D></D>
    </DPR>
    <DPR name="CashSlipTitle" id="106" x="28" px="00028" y="15" py="00100" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=007" m1="1" m2="1" attr="001" property="title alt">
      <D></D>
    </DPR>
    <DPR name="ValidationNo" id="107" x="28" px="00028" y="15" py="00050" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="validation number">
      <D></D>
    </DPR>
    <DPR name="CashSlipSeqNo" id="108" x="28" px="00028" y="15" py="00760" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="vlt sequence number alt">
      <D></D>
    </DPR>
    <DPR name="License" id="111" x="28" px="00028" y="15" py="00215" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="license alt">
      <D></D>
    </DPR>
    <DPR name="CashValue" id="114" x="28" px="00028" y="120" py="00360" dx="476" pdx="00476" dy="70" pdy="00100" rot="1" jst="2" type="F=002" m1="1" m2="1" attr="001" property="value">
      <D></D>
    </DPR>
    <DPR name="CashValueText" id="115" x="28" px="00028" y="120" py="00460" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=006" m1="1" m2="1" attr="001" property="value in wrapped words 1">
      <D></D>
    </DPR>
    <DPR name="CashValueText" id="116" x="28" px="00028" y="120" py="00500" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=006" m1="1" m2="1" attr="001" property="value in wrapped words 2">
      <D></D>
    </DPR>
    <DPR name="CashSlipBarcode" id="117" x="28" px="00028" y="120" py="00850" dx="476" pdx="00476" dy="100" pdy="00150" rot="1" jst="2" type="B=001" m1="2" m2="6" attr="080" property="barcode">
      <D></D>
    </DPR>
    <DPR name="EstablishmentName" id="121" x="28" px="00028" y="15" py="00190" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=007" m1="1" m2="1" attr="001" property="establishment name">
      <D></D>
    </DPR>
    <DPR name="Date" id="127" x="28" px="00028" y="120" py="00595" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="date">
      <D></D>
    </DPR>
    <DPR name="Time" id="128" x="28" px="00028" y="120" py="00620" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="time">
      <D></D>
    </DPR>
    <DPR name="SerialId" id="129" x="28" px="00028" y="15" py="00680" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=007" m1="1" m2="1" attr="001" property="serial id alt">
      <D></D>
    </DPR>
    <DPR name="Vendor" id="130" x="28" px="00028" y="15" py="00930" dx="540" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=006" m1="1" m2="1" attr="001" property="vendor">
      <D></D>
    </DPR>
    <DPR name="Regulator" id="131" x="28" px="00028" y="15" py="00240" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=007" m1="1" m2="1" attr="001" property="regulator">
      <D></D>
    </DPR>
    <DPR name="CashSlipTitle" id="132" x="28" px="00028" y="15" py="00730" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="title jackpot bottom">
      <D></D>
    </DPR>
	<DPR name="TextTicketLeftAlt" id="133" x="28" px="00000" y="20" py="00020" dx="476" pdx="00504" dy="2000" pdy="01000" rot="1" jst="1" type="F=009" m1="1" m2="1" attr="001" property="left alt">
      <D></D>
    </DPR>
	<DPR name="CashSlipPaperLevel" id="134" x="28" px="00028" y="85" py="00085" dx="476" pdx="00476" dy="31" pdy="00031" rot="1" jst="2" type="F=008" m1="1" m2="1" attr="001" property="paper level">
      <D></D>                                                                                                   
    </DPR>     
</DPR_Collection>
