=== tejvirc/Platform/Hardware/Aristocrat.Monaco.Hardware.Contracts/Template.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" 
           elementFormDefault="qualified" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- definition of types -->
  <xs:simpleType name="idtype">
    <xs:restriction base="xs:int">
      <xs:minExclusive value="99" />
      <xs:maxInclusive value="999" />
    </xs:restriction>
  </xs:simpleType>
  
  <!-- definition of attributes -->
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="id" type="idtype" />
  <xs:attribute name="t_dim_da" type="xs:int" default="500"/>
  <xs:attribute name="t_dim_pa" type="xs:int" default="2020"/>

  <!-- definition of complex elements -->
  <xs:complexType name="dpttype">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute ref="name" use="required" />
        <xs:attribute ref="id" use="required" />
        <xs:attribute ref="t_dim_da" />
        <xs:attribute ref="t_dim_pa" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="dptcollectiontype">
    <xs:sequence>
      <xs:element name="DPT" type="dpttype" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <!-- definition of root element -->
  <xs:element name="DPT_Collection" type="dptcollectiontype" />

</xs:schema>

=== tejvirc/Platform/Hardware/Aristocrat.Monaco.Hardware/printable_templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<DPT_Collection
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="Template.xsd">
    <DPT name="identity" id="103">134 135 136 137 138 139 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 140 158 159 160 161 162 </DPT>
	<DPT name="error" id="104">163 135 136 137 138 164 165 166 167 168 170 171 </DPT>
	<DPT name="accounting" id="105">135 136 137 138 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 </DPT>
	<DPT name="game accounting" id="106">135 136 137 138 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 </DPT>
	<DPT name="game history" id="107">270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 451 290 291 292 449 450 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 334 451 452 453 </DPT>
	<DPT name="last bills" id="109">135 136 137 351 145 146 147 148 352 353 354 355 356 357 358 138 </DPT>
	<DPT name="coupon" id="108">135 136 137 138 335 336 337 339 340 341 342 343 344 345 346 347 348 349 350 </DPT>
	<DPT name="power loss" id="110">359 360 361 </DPT>
	<DPT name="qc result" id="111">362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 </DPT>
	<DPT name="legacy cashout" id="112">380 135 136 137 138 381 382 383 998 999 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403 404 405 406 407 161 162 </DPT>
	<DPT name="legacy handpay" id="112">380 135 136 137 138 381 382 383 998 999 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403 404 405 406 407 161 162 </DPT>
	<DPT name="legacy jackpot" id="112">380 135 136 137 138 381 382 383 998 999 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403 404 405 406 407 161 162 </DPT>  
	<DPT name="cashout" id="101">102 103 104 105 106 107 113 108 109 110 111 112 125 114 115 116 117 118 119 120 121 122 123 124 101 </DPT>
	<DPT name="handpay" id="101">102 103 104 105 106 107 113 108 109 110 111 112 125 114 115 116 117 118 119 120 121 122 123 124 101 </DPT>
	<DPT name="jackpot" id="101">102 103 104 105 106 107 113 108 109 110 111 112 125 114 115 116 117 118 119 120 121 122 123 124 101 </DPT>
    <DPT name="promo" id="101">102 103 104 105 106 107 113 108 109 110 111 112 125 114 115 116 117 118 119 120 121 122 123 124 101 </DPT>
    <DPT name="handpay receipt" id="113">101 102 103 104 113 126 127 128 130 106 107 408 114 115 116 117 118 119 120 121 122 123 124 131 132 </DPT>
  <DPT name="handpay signature" id="113">101 102 103 104 113 126 127 128 130 106 107 408 114 115 116 117 118 119 120 121 122 123 124 131 132 </DPT>
  <DPT name="aft sas" id="114">409 410 411 412 413 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435 </DPT>
	<DPT name="information" id="115">437 135 136 137 138 139 438 439 440 441 442 443 444 445 446 447 456 457 448 </DPT>
    <DPT name="cashout restricted" id="102">102 103 104 113 126 127 128 130 133 114 115 116 117 118 119 120 121 122 123 124 101 131 132 106 107 </DPT>
    <DPT name="cashout offset" id="102">102 103 104 113 126 127 128 130 133 114 115 116 117 118 119 120 121 122 123 124 101 131 132 106 107 </DPT>
  <DPT name="handpay restricted" id="102">102 103 104 113 126 127 128 130 133 114 115 116 117 118 119 120 121 122 123 124 101 131 132 106 107 </DPT>
	<DPT name="handpay offset" id="102">102 103 104 113 126 127 128 130 133 114 115 116 117 118 119 120 121 122 123 124 101 131 132 106 107 </DPT>
  <DPT name="handpay receipt restricted" id="113">101 102 103 104 113 126 127 128 130 106 107 408 114 115 116 117 118 119 120 121 122 123 124 131 132 </DPT>
	<DPT name="handpay receipt offset" id="113">101 102 103 104 113 126 127 128 130 106 107 408 114 115 116 117 118 119 120 121 122 123 124 131 132 </DPT>
  <DPT name="jackpot restricted" id="102">102 103 104 113 126 127 128 130 133 114 115 116 117 118 119 120 121 122 123 124 101 131 132 106 107 </DPT>
    <DPT name="jackpot offset" id="102">102 103 104 113 126 127 128 130 133 114 115 116 117 118 119 120 121 122 123 124 101 131 132 106 107 </DPT>
  <DPT name="promo restricted" id="102">102 103 104 113 126 127 128 130 133 114 115 116 117 118 119 120 121 122 123 124 101 131 132 106 107 </DPT>
	<DPT name="promo offset" id="102">102 103 104 113 126 127 128 130 133 114 115 116 117 118 119 120 121 122 123 124 101 131 132 106 107 </DPT>
  <DPT name="jackpot receipt" id="113">101 102 103 104 113 126 127 128 130 106 107 408 114 115 116 117 118 119 120 121 122 123 124 131 132 </DPT>
	<DPT name="jackpot signature" id="113">101 102 103 104 113 126 127 128 130 106 107 408 114 115 116 117 118 119 120 121 122 123 124 131 132 </DPT>
  <DPT name="jackpot receipt restricted" id="113">101 102 103 104 113 126 127 128 130 106 107 408 114 115 116 117 118 119 120 121 122 123 124 131 132 </DPT>
	<DPT name="promo receipt" id="113">101 102 103 104 113 126 127 128 130 106 107 408 114 115 116 117 118 119 120 121 122 123 124 131 132 </DPT>
	<DPT name="promo signature" id="113">101 102 103 104 113 126 127 128 130 106 107 408 114 115 116 117 118 119 120 121 122 123 124 131 132 </DPT>
  <DPT name="promo receipt restricted" id="113">101 102 103 104 113 126 127 128 130 106 107 408 114 115 116 117 118 119 120 121 122 123 124 131 132 </DPT>
    
<DPT name="promo receipt offset" id="113">101 102 103 104 113 126 127 128 130 106 107 408 114 115 116 117 118 119 120 121 122 123 124 131 132 </DPT>
  <DPT name="Game Accounting p2" id="201">258 259 260 261 262 263 264 265 266 267 268 269 </DPT>
</DPT_Collection>
