=== tejvirc/Platform/Hardware/Aristocrat.Monaco.Hardware.Serial/Printer/PrinterOverrides.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Overrides">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="Override">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="1" name="AuditTickets">
                <xs:complexType>
                  <xs:attribute name="PlatformTemplateIds" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="TemplateChanges">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="TemplateChange">
                      <xs:complexType>
                        <xs:attribute name="Name" type="xs:string" use="required" />
                        <xs:attribute name="PlatformTemplateId" type="xs:unsignedByte" use="required" />
                        <xs:attribute name="Regions" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="Replacements">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="GlobalRegionTextReplace">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="GlobalReplace">
                            <xs:complexType>
                              <xs:attribute name="Replace" type="xs:string" use="required" />
                              <xs:attribute name="With" type="xs:string" use="required" />
                              <xs:attribute name="OnlyFirstOccurrencePerLine" type="xs:boolean" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" name="RegionTextReplace">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="TextReplace">
                            <xs:complexType>
                              <xs:attribute name="PlatformTemplateIds" type="xs:string" use="optional" default="" />
                              <xs:attribute name="RegionId" type="xs:string" use="required" />
                              <xs:attribute name="Description" type="xs:string" use="required" />
                              <xs:attribute name="Replace" type="xs:string" use="required" />
                              <xs:attribute name="With" type="xs:string" use="required" />
                              <xs:attribute name="IsReplaceRegexString" type="xs:boolean" use="optional" default="false" />
                              <xs:attribute name="LeadingText" type="xs:string" use="optional" default="" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="ChangeRegionCase">
                      <xs:complexType>
                          <xs:attribute name="RegionId" type="xs:string" use="required" />
                          <xs:attribute name="Description" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" name="TextSplitForRegion">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="Split">
                            <xs:complexType>
                              <xs:attribute name="RegionId" type="xs:string" use="required" />
                              <xs:attribute name="NewRegionId" type="xs:string" use="required" />
                              <xs:attribute name="Description" type="xs:string" use="required" />
                              <xs:attribute name="RegEx" type="xs:string" use="optional" default="" />
                              <xs:attribute name="FormatString" type="xs:string" use="optional" default="" />
                              <xs:attribute name="LeadingText" type="xs:string" use="optional" default="" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" name="TextCombine">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="RegionTextCombine">
                            <xs:complexType>
                              <xs:attribute name="PlatformTemplateIds" type="xs:string" use="required" />
                              <xs:attribute name="RegionIds" type="xs:string" use="required" />
                              <xs:attribute name="NewRegionId" type="xs:string" use="required" />
                              <xs:attribute name="LeadingText" type="xs:string" use="optional" default="" />
                              <xs:attribute name="JoinText" type="xs:string"  use="optional" default="" />
                              <xs:attribute name="TrailingText" type="xs:string"  use="optional" default="" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="NewPrinterTemplates">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="NewRegion">
                      <xs:complexType>
                        <xs:attribute name="Description" type="xs:string" use="required" />
                        <xs:attribute name="PrinterRegionId" type="xs:string" use="required" />
                        <xs:attribute name="Command" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="NewTemplate">
                      <xs:complexType>
                        <xs:attribute name="Description" type="xs:string" use="required" />
                        <xs:attribute name="PrinterTemplateId" type="xs:string" use="required" />
                        <xs:attribute name="Command" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="PrinterTemplateMappings">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="Mapping">
                      <xs:complexType>
                        <xs:attribute name="Description" type="xs:string" use="required" />
                        <xs:attribute name="PlatformTemplateId" type="xs:string" use="required" />
                        <xs:attribute name="PrinterTemplateId" type="xs:string" use="required" />
                        <xs:attribute name="Regions" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="FontOverrides">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="FontOverride">
                      <xs:complexType>
                        <xs:attribute name="RegionIds" type="xs:string" use="required" />
                        <xs:attribute name="OriginalFontNumber" type="xs:string" use="required" />
                        <xs:attribute name="NewFontNumber" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Protocol" type="xs:string" use="required" />
            <xs:attribute name="FirmwareBase" type="xs:string" use="required" />
            <xs:attribute name="UsePrinterDefinedTemplates" type="xs:boolean" use="optional" default="false" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== tejvirc/Platform/Jurisdiction/Holland/PrinterOverrides.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- 
*NOTE* When adding or removing elements to this file, you will need to 
change the corresponding xsd schema file and generate a new class definition
as follows:

1.  Open a Visual Studio command prompt and change to the directory:
    Hardware\Aristocrat.Monaco.Hardware.Serial\Printer
2.  Enter "xsd PrinterOverrides.xsd /c /n:Aristocrat.Monaco.Hardware.Serial".  This will generate
    the corresponding class definition in csharp (PrinterOverrides.cs).
-->

<!--
This file allows you to override printer templates and/or printer template mapping defined
in the printable_templates.xml and serial_printer_template_mappings.xml files based on 
the printer protocol and firmware.
The printer protocols are defined in Hardware\Aristocrat.Monaco.Hardware\SupportedDevices.xml for
a given printer model.
The printer firmware version is discovered by the platform at runtime.
-->

<!--
Please see the following link for descriptions of the elements and atributes in this file:

https://confy.aristocrat.com/display/MON/Printer+Override+XML+Element+and+Attribute+Description

Please update the confluence page when new elements and attributes are added.
 -->

<Overrides>
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../bin/Printer/PrinterOverrides.xsd">
  <Override Protocol="EpicTTL" FirmwareBase="*" UsePrinterDefinedTemplates="true" >
    <AuditTickets PlatformTemplateIds="101 105" />

    <Replacements>
      <RegionTextReplace>
        <TextReplace RegionId="129" Description="value" Replace=" " With="" LeadingText="Õ" />
        <TextReplace RegionId="114" Description="value" Replace=" " With="" LeadingText="Õ" />
      </RegionTextReplace>
      <TextSplitForRegion>
        <Split RegionId="127" NewRegionId="1" Description="Date" RegEx="(.+)\s\d{2}:\d{2}:\d{2}" LeadingText=" " />
        <Split RegionId="127" NewRegionId="2" Description="Time" RegEx=".+\s(\d{2}:\d{2}:\d{2})" />
        <Split RegionId="126" NewRegionId="1" Description="Date" RegEx="(.+)\s\d{2}:\d{2}:\d{2}" LeadingText=" " />
        <Split RegionId="126" NewRegionId="2" Description="Time" RegEx=".+\s(\d{2}:\d{2}:\d{2})" />
      </TextSplitForRegion>
    </Replacements>

    <PrinterTemplateMappings>
      <Mapping Description="cashout" PlatformTemplateId="102" PrinterTemplateId="0" Regions="107 121 125 135 106 120 107 1 2 124 115 0 114 0 118 125 117" />
      <Mapping Description="jackpot" PlatformTemplateId="103" PrinterTemplateId="1" Regions="107 121 122 135 0 129 131 132 1 2 128 120 107 0 118 125 130" />
      <Mapping Description="handpay receipt" PlatformTemplateId="104" PrinterTemplateId="1" Regions="107 121 122 135 0 129 131 132 1 2 128 120 107 0 118 125 130" />
      <Mapping Description="jackpot no barcode" PlatformTemplateId="106" PrinterTemplateId="1" Regions="0 121 122 135 0 129 131 132 1 2 0 128 0 0 118 125 0" />
      <Mapping Description="handpay receipt no barcode" PlatformTemplateId="107" PrinterTemplateId="1" Regions="0 121 122 135 0 129 131 132 1 2 0 128 0 0 118 125 0" />
    </PrinterTemplateMappings>
  </Override>
  
  
  <Override Protocol="JCM TCL" FirmwareBase="*" UsePrinterDefinedTemplates="true" >
    <AuditTickets PlatformTemplateIds="101 105" />

    <Replacements>
      <RegionTextReplace>
        <TextReplace RegionId="106" Description="title" Replace="VOUCHER" With="TICKET" />
        <TextReplace RegionId="129" Description="value" Replace=" " With="" LeadingText="Õ" />
        <TextReplace RegionId="114" Description="value" Replace=" " With="" LeadingText="Õ" />
      </RegionTextReplace>
      <TextSplitForRegion>
        <Split RegionId="127" NewRegionId="1" Description="Date" RegEx="(.+)\s\d{2}:\d{2}:\d{2}" />
        <Split RegionId="127" NewRegionId="2" Description="Time" RegEx=".+\s(\d{2}:\d{2}:\d{2})" />
        <Split RegionId="126" NewRegionId="1" Description="Date" RegEx="(.+)\s\d{2}:\d{2}:\d{2}" />
        <Split RegionId="126" NewRegionId="2" Description="Time" RegEx=".+\s(\d{2}:\d{2}:\d{2})" />
      </TextSplitForRegion>
    </Replacements>

    <PrinterTemplateMappings>
      <Mapping Description="cashout" PlatformTemplateId="102" PrinterTemplateId="0" Regions="107 121 125 135 106 0 107 1 2 124 0 0 114 0 118 125 117" />
      <Mapping Description="jackpot" PlatformTemplateId="103" PrinterTemplateId="1" Regions="107 121 125 135 0 129 107 0 1 2 0 0 0 0 118 125 130" />
      <Mapping Description="handpay receipt" PlatformTemplateId="104" PrinterTemplateId="1" Regions="107 121 125 135 0 129 107 0 1 2 0 0 0 0 118 125 130" />
      <Mapping Description="jackpot no barcode" PlatformTemplateId="106" PrinterTemplateId="1" Regions="0 121 125 135 0 129 0 0 1 2 0 0 0 0 118 125 0" />
      <Mapping Description="handpay receipt no barcode" PlatformTemplateId="107" PrinterTemplateId="1" Regions="0 121 125 135 0 129 0 0 1 2 0 0 0 0 118 125 0" />
    </PrinterTemplateMappings>
  </Override>
</Overrides>

=== tejvirc/Platform/Jurisdiction/CostaRica/PrinterOverrides.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- 
*NOTE* When adding or removing elements to this file, you will need to 
change the corresponding xsd schema file and generate a new class definition
as follows:

1.  Open a Visual Studio command prompt and change to the directory:
    Hardware\Aristocrat.Monaco.Hardware.Serial\Printer
2.  Enter "xsd PrinterOverrides.xsd /c /n:Aristocrat.Monaco.Hardware.Serial".  This will generate
    the corresponding class definition in csharp (PrinterOverrides.cs).
-->

<!--
This file allows you to override printer templates and/or printer template mapping defined
in the printable_templates.xml and serial_printer_template_mappings.xml files based on 
the printer protocol and firmware.
The printer protocols are defined in Hardware\Aristocrat.Monaco.Hardware\SupportedDevices.xml for
a given printer model.
The printer firmware version is discovered by the platform at runtime.
-->

<!--
Please see the following link for descriptions of the elements and atributes in this file:

https://confy.aristocrat.com/display/MON/Printer+Override+XML+Element+and+Attribute+Description

Please update the confluence page when new elements and attributes are added.
 -->

<Overrides>
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../bin/Printer/PrinterOverrides.xsd">
  <Override Protocol="JCM TCL" FirmwareBase="GURCRCAI2" UsePrinterDefinedTemplates="true" >
    <AuditTickets PlatformTemplateIds="101 105" />

    <Replacements>
      <RegionTextReplace>
        <TextReplace RegionId="106" Description="CashSlipTitle" Replace="SÓLO PARA JUGAR" With="SOLO PARA JUGAR" />
        <TextReplace RegionId="125" Description="machine id" Replace="MÁQUINA" With="MAQUINA" />
        <TextReplace RegionId="115" Description="CashValueText" Replace="COLÓNS" With="COLONS" />
        <TextReplace RegionId="115" Description="CashValueText" Replace="MILLÓN" With="MILLON" />
        <TextReplace RegionId="132" Description="AltCashValueText2" Replace="COLÓNS" With="COLONS" />
        <TextReplace RegionId="132" Description="AltCashValueText2" Replace="MILLÓN" With="MILLON" />
        <TextReplace RegionId="106" Description="CashSlipTitle" Replace="CUPÓN DE PAGO EN EFECTIVO" With="VALE DE PAGO" />
        <TextReplace RegionId="118" Description="redemption text" Replace="Validéz" With="Validez" />
        <TextReplace RegionId="118" Description="redemption text" Replace="días" With="dias" />
        <TextReplace RegionId="120" Description="validation title" Replace="VALIDACIÓN" With="VALIDACION" />
      </RegionTextReplace>
      <TextSplitForRegion>
        <Split RegionId="127" NewRegionId="1" Description="Date" RegEx="(.+)\s\d{2}:\d{2}:\d{2}" />
        <Split RegionId="127" NewRegionId="2" Description="Time" RegEx=".+\s(\d{2}:\d{2}:\d{2})" />
        <Split RegionId="126" NewRegionId="1" Description="Date" RegEx="(.+)\s\d{2}:\d{2}:\d{2}" />
        <Split RegionId="126" NewRegionId="2" Description="Time" RegEx=".+\s(\d{2}:\d{2}:\d{2})" />
      </TextSplitForRegion>
      <TextCombine>
        <RegionTextCombine PlatformTemplateIds="106 107" RegionIds="131 132" NewRegionId="3" JoinText="\r\n"/>
      </TextCombine>
    </Replacements>

    <PrinterTemplateMappings>
      <Mapping Description="cashout" PlatformTemplateId="102" PrinterTemplateId="2" Regions="107 121 123 106 0 120 107 1 2 124 115 114 0 118 125 117 0" />
      <Mapping Description="jackpot" PlatformTemplateId="103" PrinterTemplateId="8" Regions="107 121 123 106 0 120 107 1 2 128 3 129 0 118 125 130" />
      <Mapping Description="handpay receipt" PlatformTemplateId="104" PrinterTemplateId="8" Regions="107 121 123 106 0 120 107 1 2 128 3 129 0 118 125 130" />
      <Mapping Description="jackpot no barcode" PlatformTemplateId="106" PrinterTemplateId="8" Regions="0 121 123 106 0 0 0 1 2 128 3 129 0 0 125 0" />
      <Mapping Description="handpay receipt no barcode" PlatformTemplateId="107" PrinterTemplateId="8" Regions="0 121 123 106 0 0 0 1 2 128 3 129 0 0 125 0" />
    </PrinterTemplateMappings>
  </Override>
  
  
  <Override Protocol="JCM TCL" FirmwareBase="*" UsePrinterDefinedTemplates="true" >
    <AuditTickets PlatformTemplateIds="101 105" />

    <Replacements>
      <RegionTextReplace>
        <TextReplace RegionId="106" Description="CashSlipTitle" Replace="CUPÓN DE PAGO EN EFECTIVO" With="VALE DE PAGO" />
      </RegionTextReplace>
      <TextSplitForRegion>
        <Split RegionId="127" NewRegionId="1" Description="Date" RegEx="(.+)\s\d{2}:\d{2}:\d{2}" />
        <Split RegionId="127" NewRegionId="2" Description="Time" RegEx=".+\s(\d{2}:\d{2}:\d{2})" />
        <Split RegionId="126" NewRegionId="1" Description="Date" RegEx="(.+)\s\d{2}:\d{2}:\d{2}" />
        <Split RegionId="126" NewRegionId="2" Description="Time" RegEx=".+\s(\d{2}:\d{2}:\d{2})" />
      </TextSplitForRegion>
      <TextCombine>
        <RegionTextCombine PlatformTemplateIds="106 107" RegionIds="131 132" NewRegionId="3" JoinText="\r\n"/>
      </TextCombine>
    </Replacements>

    <PrinterTemplateMappings>
      <Mapping Description="cashout" PlatformTemplateId="102" PrinterTemplateId="2" Regions="107 121 123 106 0 120 107 1 2 124 115 114 0 118 125 117 0" />
      <Mapping Description="jackpot" PlatformTemplateId="103" PrinterTemplateId="8" Regions="107 121 123 106 0 120 107 1 2 128 3 129 0 118 125 130" />
      <Mapping Description="handpay receipt" PlatformTemplateId="104" PrinterTemplateId="8" Regions="107 121 123 106 0 120 107 1 2 128 3 129 0 118 125 130" />
      <Mapping Description="jackpot no barcode" PlatformTemplateId="106" PrinterTemplateId="8" Regions="0 121 123 106 0 0 0 1 2 128 3 129 0 0 125 0" />
      <Mapping Description="handpay receipt no barcode" PlatformTemplateId="107" PrinterTemplateId="8" Regions="0 121 123 106 0 0 0 1 2 128 3 129 0 0 125 0" />
    </PrinterTemplateMappings>
  </Override>


  <Override Protocol="JCM TCL" FirmwareBase="*" UsePrinterDefinedTemplates="true" >
    <AuditTickets PlatformTemplateIds="101 105" />

    <Replacements>
      <RegionTextReplace>
        <TextReplace RegionId="106" Description="CashSlipTitle" Replace="CASHWIN TICKET" With="VALE DE PAGO" />
        <TextReplace RegionId="106" Description="CashSlipTitle" Replace="CASHWIN VOUCHER" With="VALE DE PAGO" />
        <TextReplace RegionId="106" Description="CashSlipTitle" Replace="CUPÓN DE PAGO EN EFECTIVO" With="VALE DE PAGO" />
      </RegionTextReplace>
      <TextSplitForRegion>
        <Split RegionId="127" NewRegionId="1" Description="Date" RegEx="(.+)\s\d{2}:\d{2}:\d{2}" />
        <Split RegionId="127" NewRegionId="2" Description="Time" RegEx=".+\s(\d{2}:\d{2}:\d{2})" />
        <Split RegionId="126" NewRegionId="1" Description="Date" RegEx="(.+)\s\d{2}:\d{2}:\d{2}" />
        <Split RegionId="126" NewRegionId="2" Description="Time" RegEx=".+\s(\d{2}:\d{2}:\d{2})" />
      </TextSplitForRegion>
      <TextCombine>
        <RegionTextCombine PlatformTemplateIds="106 107" RegionIds="131 132" NewRegionId="3" JoinText="\r\n"/>
      </TextCombine>
    </Replacements>

    <PrinterTemplateMappings>
      <Mapping Description="cashout" PlatformTemplateId="102" PrinterTemplateId="2" Regions="107 121 123 106 0 120 107 1 2 124 115 114 0 118 125 117 0" />
      <Mapping Description="jackpot" PlatformTemplateId="103" PrinterTemplateId="8" Regions="107 121 123 106 0 120 107 1 2 128 3 129 0 118 125 130" />
      <Mapping Description="handpay receipt" PlatformTemplateId="104" PrinterTemplateId="8" Regions="107 121 123 106 0 120 107 1 2 128 3 129 0 118 125 130" />
      <Mapping Description="jackpot no barcode" PlatformTemplateId="106" PrinterTemplateId="8" Regions="0 121 123 106 0 0 0 1 2 128 3 129 0 0 125 0" />
      <Mapping Description="handpay receipt no barcode" PlatformTemplateId="107" PrinterTemplateId="8" Regions="0 121 123 106 0 0 0 1 2 128 3 129 0 0 125 0" />
    </PrinterTemplateMappings>
  </Override>
</Overrides>
